# Generated by Django 2.2.5 on 2019-09-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChinamobileApp',
            fields=[
                ('id', models.AutoField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('speedlimit', models.CharField(blank=True, max_length=50, null=True)),
                ('callbeyondfee', models.CharField(blank=True, max_length=50, null=True)),
                ('show_total_call', models.CharField(blank=True, max_length=50, null=True)),
                ('dingxiang_flow', models.CharField(blank=True, max_length=50, null=True)),
                ('callanswer', models.CharField(blank=True, max_length=50, null=True)),
                ('flowbeyondfee', models.CharField(blank=True, max_length=200, null=True)),
                ('v_4g_kd_new', models.CharField(blank=True, max_length=50, null=True)),
                ('tariffdesc', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'chinamobile_app',
            },
        ),
        migrations.CreateModel(
            name='Chinatelecom',
            fields=[
                ('id', models.AutoField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('fee', models.CharField(blank=True, max_length=20, null=True)),
                ('flow', models.CharField(blank=True, max_length=20, null=True)),
                ('call', models.CharField(blank=True, max_length=20, null=True)),
                ('sec_card', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'chinatelecom',
            },
        ),
        migrations.CreateModel(
            name='Chinaunicom',
            fields=[
                ('id', models.AutoField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('typename1', models.CharField(blank=True, db_column='typeName1', max_length=50, null=True)),
                ('typename2', models.CharField(blank=True, db_column='typeName2', max_length=50, null=True)),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('title2', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('detail_url', models.CharField(blank=True, max_length=200, null=True)),
                ('invoicetime', models.CharField(blank=True, db_column='inVoicetime', max_length=50, null=True)),
                ('inflowgn', models.CharField(blank=True, db_column='inFlowgn', max_length=50, null=True)),
                ('inincrementbusiness', models.CharField(blank=True, db_column='inIncrementbusiness', max_length=50, null=True)),
                ('infreeanswer', models.CharField(blank=True, db_column='inFreeanswer', max_length=50, null=True)),
                ('extravoicetime', models.CharField(blank=True, db_column='extraVoicetime', max_length=50, null=True)),
                ('extrasms', models.CharField(blank=True, db_column='extraSms', max_length=50, null=True)),
                ('extraotherbusiness', models.CharField(blank=True, db_column='extraOtherbusiness', max_length=50, null=True)),
                ('combofeatures', models.CharField(blank=True, max_length=2000, null=True)),
                ('extraflowgnadd', models.CharField(blank=True, db_column='extraFlowgnAdd', max_length=200, null=True)),
                ('addprivilege', models.CharField(blank=True, db_column='addPrivilege', max_length=50, null=True)),
            ],
            options={
                'db_table': 'chinaunicom',
            },
        ),
        migrations.CreateModel(
            name='ChinaunicomAppPkg',
            fields=[
                ('id', models.AutoField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('fee', models.CharField(blank=True, max_length=20, null=True)),
                ('flow', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'chinaunicom_app_pkg',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('goodsname', models.CharField(blank=True, db_column='goodsName', max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('weburl', models.CharField(blank=True, db_column='webUrl', max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('provider', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mobile',
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(default=1, max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('evalnum', models.CharField(blank=True, db_column='evalNum', max_length=10, null=True)),
                ('detail_url', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phones',
            },
        ),
    ]
